//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace WindowsFormsApp1
{

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GrammarBaseListener : IGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] GrammarParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] GrammarParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.functionHeading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionHeading([NotNull] GrammarParser.FunctionHeadingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.functionHeading"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionHeading([NotNull] GrammarParser.FunctionHeadingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] GrammarParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] GrammarParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] GrammarParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] GrammarParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.usesUnitsPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsesUnitsPart([NotNull] GrammarParser.UsesUnitsPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.usesUnitsPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsesUnitsPart([NotNull] GrammarParser.UsesUnitsPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.labelDeclarationPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabelDeclarationPart([NotNull] GrammarParser.LabelDeclarationPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.labelDeclarationPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabelDeclarationPart([NotNull] GrammarParser.LabelDeclarationPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] GrammarParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] GrammarParser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.constantDefinitionPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantDefinitionPart([NotNull] GrammarParser.ConstantDefinitionPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.constantDefinitionPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantDefinitionPart([NotNull] GrammarParser.ConstantDefinitionPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.constantDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantDefinition([NotNull] GrammarParser.ConstantDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.constantDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantDefinition([NotNull] GrammarParser.ConstantDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.constantChr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantChr([NotNull] GrammarParser.ConstantChrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.constantChr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantChr([NotNull] GrammarParser.ConstantChrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] GrammarParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] GrammarParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unsignedNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnsignedNumber([NotNull] GrammarParser.UnsignedNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unsignedNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnsignedNumber([NotNull] GrammarParser.UnsignedNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unsignedInteger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnsignedInteger([NotNull] GrammarParser.UnsignedIntegerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unsignedInteger"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnsignedInteger([NotNull] GrammarParser.UnsignedIntegerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unsignedReal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnsignedReal([NotNull] GrammarParser.UnsignedRealContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unsignedReal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnsignedReal([NotNull] GrammarParser.UnsignedRealContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.sign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSign([NotNull] GrammarParser.SignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.sign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSign([NotNull] GrammarParser.SignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.bool_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBool_([NotNull] GrammarParser.Bool_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.bool_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBool_([NotNull] GrammarParser.Bool_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] GrammarParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] GrammarParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.typeDefinitionPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDefinitionPart([NotNull] GrammarParser.TypeDefinitionPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.typeDefinitionPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDefinitionPart([NotNull] GrammarParser.TypeDefinitionPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.typeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeDefinition([NotNull] GrammarParser.TypeDefinitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.typeDefinition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeDefinition([NotNull] GrammarParser.TypeDefinitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.procedureType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureType([NotNull] GrammarParser.ProcedureTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.procedureType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureType([NotNull] GrammarParser.ProcedureTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_([NotNull] GrammarParser.Type_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_([NotNull] GrammarParser.Type_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.simpleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleType([NotNull] GrammarParser.SimpleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.simpleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleType([NotNull] GrammarParser.SimpleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.scalarType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalarType([NotNull] GrammarParser.ScalarTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.scalarType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalarType([NotNull] GrammarParser.ScalarTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.subrangeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubrangeType([NotNull] GrammarParser.SubrangeTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.subrangeType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubrangeType([NotNull] GrammarParser.SubrangeTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.typeIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeIdentifier([NotNull] GrammarParser.TypeIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.typeIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeIdentifier([NotNull] GrammarParser.TypeIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.structuredType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructuredType([NotNull] GrammarParser.StructuredTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.structuredType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructuredType([NotNull] GrammarParser.StructuredTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unpackedStructuredType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnpackedStructuredType([NotNull] GrammarParser.UnpackedStructuredTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unpackedStructuredType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnpackedStructuredType([NotNull] GrammarParser.UnpackedStructuredTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.stringtype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringtype([NotNull] GrammarParser.StringtypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.stringtype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringtype([NotNull] GrammarParser.StringtypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayType([NotNull] GrammarParser.ArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayType([NotNull] GrammarParser.ArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.typeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeList([NotNull] GrammarParser.TypeListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.typeList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeList([NotNull] GrammarParser.TypeListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.indexType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIndexType([NotNull] GrammarParser.IndexTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.indexType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIndexType([NotNull] GrammarParser.IndexTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.componentType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComponentType([NotNull] GrammarParser.ComponentTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.componentType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComponentType([NotNull] GrammarParser.ComponentTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.recordType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordType([NotNull] GrammarParser.RecordTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.recordType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordType([NotNull] GrammarParser.RecordTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fieldList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldList([NotNull] GrammarParser.FieldListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fieldList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldList([NotNull] GrammarParser.FieldListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fixedPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFixedPart([NotNull] GrammarParser.FixedPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fixedPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFixedPart([NotNull] GrammarParser.FixedPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.recordSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordSection([NotNull] GrammarParser.RecordSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.recordSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordSection([NotNull] GrammarParser.RecordSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.variantPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariantPart([NotNull] GrammarParser.VariantPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.variantPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariantPart([NotNull] GrammarParser.VariantPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTag([NotNull] GrammarParser.TagContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.tag"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTag([NotNull] GrammarParser.TagContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.variant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariant([NotNull] GrammarParser.VariantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.variant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariant([NotNull] GrammarParser.VariantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.setType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetType([NotNull] GrammarParser.SetTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.setType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetType([NotNull] GrammarParser.SetTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.baseType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseType([NotNull] GrammarParser.BaseTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.baseType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseType([NotNull] GrammarParser.BaseTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fileType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileType([NotNull] GrammarParser.FileTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fileType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileType([NotNull] GrammarParser.FileTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.pointerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointerType([NotNull] GrammarParser.PointerTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.pointerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointerType([NotNull] GrammarParser.PointerTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.variableDeclarationPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarationPart([NotNull] GrammarParser.VariableDeclarationPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.variableDeclarationPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarationPart([NotNull] GrammarParser.VariableDeclarationPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclaration([NotNull] GrammarParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.variableDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclaration([NotNull] GrammarParser.VariableDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.procedureDeclarationPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDeclarationPart([NotNull] GrammarParser.ProcedureDeclarationPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.procedureDeclarationPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDeclarationPart([NotNull] GrammarParser.ProcedureDeclarationPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.procedureDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureDeclaration([NotNull] GrammarParser.ProcedureDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.procedureDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureDeclaration([NotNull] GrammarParser.ProcedureDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterList([NotNull] GrammarParser.FormalParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.formalParameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterList([NotNull] GrammarParser.FormalParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.formalParameterSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormalParameterSection([NotNull] GrammarParser.FormalParameterSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.formalParameterSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormalParameterSection([NotNull] GrammarParser.FormalParameterSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parameterGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterGroup([NotNull] GrammarParser.ParameterGroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parameterGroup"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterGroup([NotNull] GrammarParser.ParameterGroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierList([NotNull] GrammarParser.IdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierList([NotNull] GrammarParser.IdentifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.constList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstList([NotNull] GrammarParser.ConstListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.constList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstList([NotNull] GrammarParser.ConstListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.resultType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterResultType([NotNull] GrammarParser.ResultTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.resultType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitResultType([NotNull] GrammarParser.ResultTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] GrammarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] GrammarParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unlabelledStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnlabelledStatement([NotNull] GrammarParser.UnlabelledStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unlabelledStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnlabelledStatement([NotNull] GrammarParser.UnlabelledStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.simpleStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleStatement([NotNull] GrammarParser.SimpleStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.simpleStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleStatement([NotNull] GrammarParser.SimpleStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.assignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentStatement([NotNull] GrammarParser.AssignmentStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.assignmentStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentStatement([NotNull] GrammarParser.AssignmentStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] GrammarParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] GrammarParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] GrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] GrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.relationaloperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationaloperator([NotNull] GrammarParser.RelationaloperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.relationaloperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationaloperator([NotNull] GrammarParser.RelationaloperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.simpleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleExpression([NotNull] GrammarParser.SimpleExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.simpleExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleExpression([NotNull] GrammarParser.SimpleExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.additiveoperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditiveoperator([NotNull] GrammarParser.AdditiveoperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.additiveoperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditiveoperator([NotNull] GrammarParser.AdditiveoperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] GrammarParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] GrammarParser.TermContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.multiplicativeoperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicativeoperator([NotNull] GrammarParser.MultiplicativeoperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.multiplicativeoperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicativeoperator([NotNull] GrammarParser.MultiplicativeoperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.signedFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSignedFactor([NotNull] GrammarParser.SignedFactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.signedFactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSignedFactor([NotNull] GrammarParser.SignedFactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] GrammarParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] GrammarParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unsignedConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnsignedConstant([NotNull] GrammarParser.UnsignedConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unsignedConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnsignedConstant([NotNull] GrammarParser.UnsignedConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.functionDesignator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDesignator([NotNull] GrammarParser.FunctionDesignatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.functionDesignator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDesignator([NotNull] GrammarParser.FunctionDesignatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] GrammarParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] GrammarParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.set_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSet_([NotNull] GrammarParser.Set_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.set_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSet_([NotNull] GrammarParser.Set_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.elementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementList([NotNull] GrammarParser.ElementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.elementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementList([NotNull] GrammarParser.ElementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] GrammarParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] GrammarParser.ElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.procedureStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProcedureStatement([NotNull] GrammarParser.ProcedureStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.procedureStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProcedureStatement([NotNull] GrammarParser.ProcedureStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.actualParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActualParameter([NotNull] GrammarParser.ActualParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.actualParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActualParameter([NotNull] GrammarParser.ActualParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parameterwidth"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterwidth([NotNull] GrammarParser.ParameterwidthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parameterwidth"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterwidth([NotNull] GrammarParser.ParameterwidthContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.gotoStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotoStatement([NotNull] GrammarParser.GotoStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.gotoStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotoStatement([NotNull] GrammarParser.GotoStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.exitStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExitStatement([NotNull] GrammarParser.ExitStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.exitStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExitStatement([NotNull] GrammarParser.ExitStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.emptyStatement_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyStatement_([NotNull] GrammarParser.EmptyStatement_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.emptyStatement_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyStatement_([NotNull] GrammarParser.EmptyStatement_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.empty_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmpty_([NotNull] GrammarParser.Empty_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.empty_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmpty_([NotNull] GrammarParser.Empty_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.structuredStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructuredStatement([NotNull] GrammarParser.StructuredStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.structuredStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructuredStatement([NotNull] GrammarParser.StructuredStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatements([NotNull] GrammarParser.StatementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.statements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatements([NotNull] GrammarParser.StatementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.conditionalStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalStatement([NotNull] GrammarParser.ConditionalStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.conditionalStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalStatement([NotNull] GrammarParser.ConditionalStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.elseCaseEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseCaseEnd([NotNull] GrammarParser.ElseCaseEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.elseCaseEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseCaseEnd([NotNull] GrammarParser.ElseCaseEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] GrammarParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] GrammarParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] GrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] GrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.caseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseStatement([NotNull] GrammarParser.CaseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.caseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseStatement([NotNull] GrammarParser.CaseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.caseListElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseListElement([NotNull] GrammarParser.CaseListElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.caseListElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseListElement([NotNull] GrammarParser.CaseListElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.repetetiveStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepetetiveStatement([NotNull] GrammarParser.RepetetiveStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.repetetiveStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepetetiveStatement([NotNull] GrammarParser.RepetetiveStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileStatement([NotNull] GrammarParser.WhileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.whileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileStatement([NotNull] GrammarParser.WhileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.repeatStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeatStatement([NotNull] GrammarParser.RepeatStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.repeatStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeatStatement([NotNull] GrammarParser.RepeatStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForStatement([NotNull] GrammarParser.ForStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.forStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForStatement([NotNull] GrammarParser.ForStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.forList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForList([NotNull] GrammarParser.ForListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.forList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForList([NotNull] GrammarParser.ForListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.initialValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitialValue([NotNull] GrammarParser.InitialValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.initialValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitialValue([NotNull] GrammarParser.InitialValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.finalValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFinalValue([NotNull] GrammarParser.FinalValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.finalValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFinalValue([NotNull] GrammarParser.FinalValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.withStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWithStatement([NotNull] GrammarParser.WithStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.withStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWithStatement([NotNull] GrammarParser.WithStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.recordVariableList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecordVariableList([NotNull] GrammarParser.RecordVariableListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.recordVariableList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecordVariableList([NotNull] GrammarParser.RecordVariableListContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace StoCPP
