//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar.g4 by ANTLR 4.9.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace WindowsFormsApp1 {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.3")]
[System.CLSCompliant(false)]
public interface IGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] GrammarParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] GrammarParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.functionHeading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionHeading([NotNull] GrammarParser.FunctionHeadingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.functionHeading"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionHeading([NotNull] GrammarParser.FunctionHeadingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] GrammarParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] GrammarParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] GrammarParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] GrammarParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.usesUnitsPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsesUnitsPart([NotNull] GrammarParser.UsesUnitsPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.usesUnitsPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsesUnitsPart([NotNull] GrammarParser.UsesUnitsPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.labelDeclarationPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabelDeclarationPart([NotNull] GrammarParser.LabelDeclarationPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.labelDeclarationPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabelDeclarationPart([NotNull] GrammarParser.LabelDeclarationPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] GrammarParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] GrammarParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.constantDefinitionPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantDefinitionPart([NotNull] GrammarParser.ConstantDefinitionPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.constantDefinitionPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantDefinitionPart([NotNull] GrammarParser.ConstantDefinitionPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.constantDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantDefinition([NotNull] GrammarParser.ConstantDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.constantDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantDefinition([NotNull] GrammarParser.ConstantDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.constantChr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantChr([NotNull] GrammarParser.ConstantChrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.constantChr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantChr([NotNull] GrammarParser.ConstantChrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] GrammarParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] GrammarParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unsignedNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnsignedNumber([NotNull] GrammarParser.UnsignedNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unsignedNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnsignedNumber([NotNull] GrammarParser.UnsignedNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unsignedInteger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnsignedInteger([NotNull] GrammarParser.UnsignedIntegerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unsignedInteger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnsignedInteger([NotNull] GrammarParser.UnsignedIntegerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unsignedReal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnsignedReal([NotNull] GrammarParser.UnsignedRealContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unsignedReal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnsignedReal([NotNull] GrammarParser.UnsignedRealContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSign([NotNull] GrammarParser.SignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.sign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSign([NotNull] GrammarParser.SignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.bool_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBool_([NotNull] GrammarParser.Bool_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.bool_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBool_([NotNull] GrammarParser.Bool_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] GrammarParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] GrammarParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.typeDefinitionPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDefinitionPart([NotNull] GrammarParser.TypeDefinitionPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.typeDefinitionPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDefinitionPart([NotNull] GrammarParser.TypeDefinitionPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeDefinition([NotNull] GrammarParser.TypeDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.typeDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeDefinition([NotNull] GrammarParser.TypeDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.procedureType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureType([NotNull] GrammarParser.ProcedureTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.procedureType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureType([NotNull] GrammarParser.ProcedureTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_([NotNull] GrammarParser.Type_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_([NotNull] GrammarParser.Type_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleType([NotNull] GrammarParser.SimpleTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleType([NotNull] GrammarParser.SimpleTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterScalarType([NotNull] GrammarParser.ScalarTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.scalarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitScalarType([NotNull] GrammarParser.ScalarTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.subrangeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubrangeType([NotNull] GrammarParser.SubrangeTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.subrangeType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubrangeType([NotNull] GrammarParser.SubrangeTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.typeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeIdentifier([NotNull] GrammarParser.TypeIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.typeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeIdentifier([NotNull] GrammarParser.TypeIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.structuredType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructuredType([NotNull] GrammarParser.StructuredTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.structuredType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructuredType([NotNull] GrammarParser.StructuredTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unpackedStructuredType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnpackedStructuredType([NotNull] GrammarParser.UnpackedStructuredTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unpackedStructuredType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnpackedStructuredType([NotNull] GrammarParser.UnpackedStructuredTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.stringtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringtype([NotNull] GrammarParser.StringtypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.stringtype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringtype([NotNull] GrammarParser.StringtypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayType([NotNull] GrammarParser.ArrayTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayType([NotNull] GrammarParser.ArrayTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeList([NotNull] GrammarParser.TypeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.typeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeList([NotNull] GrammarParser.TypeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.indexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexType([NotNull] GrammarParser.IndexTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.indexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexType([NotNull] GrammarParser.IndexTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.componentType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComponentType([NotNull] GrammarParser.ComponentTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.componentType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComponentType([NotNull] GrammarParser.ComponentTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.recordType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordType([NotNull] GrammarParser.RecordTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.recordType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordType([NotNull] GrammarParser.RecordTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fieldList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldList([NotNull] GrammarParser.FieldListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fieldList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldList([NotNull] GrammarParser.FieldListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fixedPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFixedPart([NotNull] GrammarParser.FixedPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fixedPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFixedPart([NotNull] GrammarParser.FixedPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.recordSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordSection([NotNull] GrammarParser.RecordSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.recordSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordSection([NotNull] GrammarParser.RecordSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.variantPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariantPart([NotNull] GrammarParser.VariantPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.variantPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariantPart([NotNull] GrammarParser.VariantPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTag([NotNull] GrammarParser.TagContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.tag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTag([NotNull] GrammarParser.TagContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.variant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariant([NotNull] GrammarParser.VariantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.variant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariant([NotNull] GrammarParser.VariantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.setType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetType([NotNull] GrammarParser.SetTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.setType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetType([NotNull] GrammarParser.SetTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseType([NotNull] GrammarParser.BaseTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseType([NotNull] GrammarParser.BaseTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fileType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileType([NotNull] GrammarParser.FileTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fileType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileType([NotNull] GrammarParser.FileTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.pointerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerType([NotNull] GrammarParser.PointerTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.pointerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerType([NotNull] GrammarParser.PointerTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.variableDeclarationPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarationPart([NotNull] GrammarParser.VariableDeclarationPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.variableDeclarationPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarationPart([NotNull] GrammarParser.VariableDeclarationPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] GrammarParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] GrammarParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.procedureDeclarationPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureDeclarationPart([NotNull] GrammarParser.ProcedureDeclarationPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.procedureDeclarationPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureDeclarationPart([NotNull] GrammarParser.ProcedureDeclarationPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.procedureDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureDeclaration([NotNull] GrammarParser.ProcedureDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.procedureDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureDeclaration([NotNull] GrammarParser.ProcedureDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameterList([NotNull] GrammarParser.FormalParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.formalParameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameterList([NotNull] GrammarParser.FormalParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.formalParameterSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameterSection([NotNull] GrammarParser.FormalParameterSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.formalParameterSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameterSection([NotNull] GrammarParser.FormalParameterSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parameterGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterGroup([NotNull] GrammarParser.ParameterGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parameterGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterGroup([NotNull] GrammarParser.ParameterGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierList([NotNull] GrammarParser.IdentifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierList([NotNull] GrammarParser.IdentifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.constList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstList([NotNull] GrammarParser.ConstListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.constList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstList([NotNull] GrammarParser.ConstListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.resultType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResultType([NotNull] GrammarParser.ResultTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.resultType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResultType([NotNull] GrammarParser.ResultTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unlabelledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnlabelledStatement([NotNull] GrammarParser.UnlabelledStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unlabelledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnlabelledStatement([NotNull] GrammarParser.UnlabelledStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.simpleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleStatement([NotNull] GrammarParser.SimpleStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.simpleStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleStatement([NotNull] GrammarParser.SimpleStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStatement([NotNull] GrammarParser.AssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStatement([NotNull] GrammarParser.AssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] GrammarParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] GrammarParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] GrammarParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] GrammarParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.relationaloperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationaloperator([NotNull] GrammarParser.RelationaloperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.relationaloperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationaloperator([NotNull] GrammarParser.RelationaloperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleExpression([NotNull] GrammarParser.SimpleExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.simpleExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleExpression([NotNull] GrammarParser.SimpleExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.additiveoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveoperator([NotNull] GrammarParser.AdditiveoperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.additiveoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveoperator([NotNull] GrammarParser.AdditiveoperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerm([NotNull] GrammarParser.TermContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerm([NotNull] GrammarParser.TermContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.multiplicativeoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeoperator([NotNull] GrammarParser.MultiplicativeoperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.multiplicativeoperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeoperator([NotNull] GrammarParser.MultiplicativeoperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.signedFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSignedFactor([NotNull] GrammarParser.SignedFactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.signedFactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSignedFactor([NotNull] GrammarParser.SignedFactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] GrammarParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] GrammarParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.unsignedConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnsignedConstant([NotNull] GrammarParser.UnsignedConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.unsignedConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnsignedConstant([NotNull] GrammarParser.UnsignedConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.functionDesignator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDesignator([NotNull] GrammarParser.FunctionDesignatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.functionDesignator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDesignator([NotNull] GrammarParser.FunctionDesignatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterList([NotNull] GrammarParser.ParameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterList([NotNull] GrammarParser.ParameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.set_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSet_([NotNull] GrammarParser.Set_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.set_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSet_([NotNull] GrammarParser.Set_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.elementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElementList([NotNull] GrammarParser.ElementListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.elementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElementList([NotNull] GrammarParser.ElementListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement([NotNull] GrammarParser.ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement([NotNull] GrammarParser.ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.procedureStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureStatement([NotNull] GrammarParser.ProcedureStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.procedureStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureStatement([NotNull] GrammarParser.ProcedureStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.actualParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActualParameter([NotNull] GrammarParser.ActualParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.actualParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActualParameter([NotNull] GrammarParser.ActualParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parameterwidth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterwidth([NotNull] GrammarParser.ParameterwidthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parameterwidth"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterwidth([NotNull] GrammarParser.ParameterwidthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotoStatement([NotNull] GrammarParser.GotoStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotoStatement([NotNull] GrammarParser.GotoStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.exitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExitStatement([NotNull] GrammarParser.ExitStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.exitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExitStatement([NotNull] GrammarParser.ExitStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.emptyStatement_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyStatement_([NotNull] GrammarParser.EmptyStatement_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.emptyStatement_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyStatement_([NotNull] GrammarParser.EmptyStatement_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.empty_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty_([NotNull] GrammarParser.Empty_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.empty_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty_([NotNull] GrammarParser.Empty_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.structuredStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructuredStatement([NotNull] GrammarParser.StructuredStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.structuredStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructuredStatement([NotNull] GrammarParser.StructuredStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatements([NotNull] GrammarParser.StatementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.statements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatements([NotNull] GrammarParser.StatementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.conditionalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalStatement([NotNull] GrammarParser.ConditionalStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.conditionalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalStatement([NotNull] GrammarParser.ConditionalStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.elseCaseEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseCaseEnd([NotNull] GrammarParser.ElseCaseEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.elseCaseEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseCaseEnd([NotNull] GrammarParser.ElseCaseEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStatement([NotNull] GrammarParser.ElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStatement([NotNull] GrammarParser.ElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] GrammarParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] GrammarParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseStatement([NotNull] GrammarParser.CaseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.caseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseStatement([NotNull] GrammarParser.CaseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.caseListElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseListElement([NotNull] GrammarParser.CaseListElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.caseListElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseListElement([NotNull] GrammarParser.CaseListElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.repetetiveStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepetetiveStatement([NotNull] GrammarParser.RepetetiveStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.repetetiveStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepetetiveStatement([NotNull] GrammarParser.RepetetiveStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] GrammarParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] GrammarParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatStatement([NotNull] GrammarParser.RepeatStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatStatement([NotNull] GrammarParser.RepeatStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForStatement([NotNull] GrammarParser.ForStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.forStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForStatement([NotNull] GrammarParser.ForStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.forList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForList([NotNull] GrammarParser.ForListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.forList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForList([NotNull] GrammarParser.ForListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.initialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitialValue([NotNull] GrammarParser.InitialValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.initialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitialValue([NotNull] GrammarParser.InitialValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.finalValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFinalValue([NotNull] GrammarParser.FinalValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.finalValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFinalValue([NotNull] GrammarParser.FinalValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.withStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithStatement([NotNull] GrammarParser.WithStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.withStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithStatement([NotNull] GrammarParser.WithStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.recordVariableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecordVariableList([NotNull] GrammarParser.RecordVariableListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.recordVariableList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecordVariableList([NotNull] GrammarParser.RecordVariableListContext context);
}
} // namespace StoCPP
